[package]
name = "raytracer"
version = "0.1.0"
authors = ["DESKTOP-5ME1J2H\\David <david@peripherallabs.com>"]

[dependencies]
image = "0.19.0"
rand = "0.5"
rayon = "1.0.2"
atomic-counter = "0.1.0"

[profile.dev]
opt-level = 3